# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net
name: $(semanticVersion)-build$(rev:rrr)

trigger:
  - master

pool: default

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  buildArtifactStaging: '$(Build.ArtifactStagingDirectory)'
  projectFile: 'KeyLogger/KeyLogger.csproj'

steps:
  - task: NuGetToolInstaller@1

  - task: CmdLine@2
    inputs:
      script: |
        echo  'Default Working Directory: $(System.DefaultWorkingDirectory)'
        echo  'Pipeline Workspace: $(Pipeline.Workspace)'
        dir
    displayName: Show working directory

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: DotNetCoreCLI@2
    displayName: 'Run tests with code coverage'
    inputs:
      command: 'test'
      projects: '$(solution)'
      arguments: '--configuration $(buildConfiguration) --collect:"XPlat Code Coverage" --results-directory $(Agent.TempDirectory)/TestResults'

  - task: PublishCodeCoverageResults@2
    displayName: Publish code coverage
    inputs:
      summaryFileLocation: '$(Agent.TempDirectory)/**/coverage.cobertura.xml'

  - task: DotNetCoreCLI@2
    displayName: 'Publish KeyLogger WPF Application'
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '$(projectFile)'
      arguments: '--configuration $(buildConfiguration) --output $(buildArtifactStaging)\publish_output'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(buildArtifactStaging)'
      Contents: '**/*'
      TargetFolder: drop
    displayName: 'Copy files to drop folder'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: drop
