<Project>
  <PropertyGroup>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <PublishForAWSLambda>false</PublishForAWSLambda>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <VersionPrefix Condition="'$(SEMANTICVERSION)' != ''">$(SEMANTICVERSION)</VersionPrefix>
    <VersionPrefix Condition="'$(SEMANTICVERSION)' == ''">1.0.0</VersionPrefix>
    <VersionSuffix>build$([MSBuild]::ValueOrDefault('$(BUILD_BUILDNUMBER)', '0'))</VersionSuffix>
  </PropertyGroup>
</Project>
